before_script:
- psql -c 'create database travis_ci_test;' -U postgres
language: ruby
rvm:
- 2.4.1
script:
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
services: postgresql
deploy:
  api_key:
    secure: YU8vV3YwiBmQlna7FKXUwLgM4zsU7rbUbcvOnpSAfZoduxZBY8jQV+lU0E1lTGjl51AX5bfZ/C9pr9thvpF8KurUygctN1IhyuJcZbZ4ib/SAfw6gf6Hds5bspzKxYQQDTwb6u8eUMfLjvIMcI33eajErS/aXbx1RVD/UvnlWXCjFDKbJfx3u6WEZ7mM3ffnQHwXIm/0BL0LvLK/FFmOC8XDwEve8U7cNNn5gFjZSTXyrmzbL/48kBQJjac4ognz36TtI5CAjdFpgw0pP2brGh1g6QvLqS4VSY0Utv86oudBl0LXlDExkS3Gv3jaOVjNQktO2f88epOh9KRYVzxchiNe1KZE0FVMGuFadDmyuq/cLdUe4Hmlw3/TidJfPPki3pzYcBj1UDVENGKASd1rab/4ILSPE0lJRLP5fyoD+nn1Hk9Qx361GAgkQXWlWRaw0lCsef2q9hnhgOW8O5luXsbd3ra8jcX/c5BJccJfCurZpTxHmiqE875WPtp/pPm5t2Dyry4qnNx0lUUdn8gcJnzUbLPRTSJOTjP85NymqDWykReLjfCVjxxidSptO0odSDaQiUyZKQz4MmI2eU4fBTik7KsgEJH9mrpJXPN2rwCAKnb3lzDcMFm3G1gzpTxCDRHUdXBnvS73Ft7hOW/QZbl/bm9pjSgJX5uIqMimw1Y=
