before_script:
- psql -c 'create database travis_ci_test;' -U postgres
language: ruby
rvm:
- 2.4.1
script:
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
services: postgresql
deploy:
  api_key:
    secure: TFPGwI0x3trqf30M3N0bJyKGh2WaNEwTgdkmemD5kkEXyTDCGjEwAMWhrRkOYiATYEq7sccmwjiUPw4CQ7fAuxxyVvGlvN0hnuYiSP0dM6byjSc7us5iycLxr+gVhIgn8PhZRpGyYVilIBk4WXCtH64N9LxJuZYzUfJaRMMsIJ/f2duSidili9rXVtPaYuIcI8LXkFJDI0zY91NwWrSbqDO61Is7FaH36bs029i12xfYYqgnq/9T32zbny7FqdEqGLhSGP4jdsA68XBpyukrbWZ2Oca2mxGMooL8OU45sscVKhK4WTcDODLV4PB1O7W5XqGwEjZEt3s/4xfy1mTITQ9gb7XUcuiIto51VpdEDbSwmvcpT3Zjz15nmMCjRpEuawybKp3koa2/LaBvzBulvKO4Eg1sD5jTXVVQewolN1lGPPjp3x+Gk3bmaC+HTsNAGUnYblngqJitH6ArV0IzIAXJOx3/LdpZ88Ei8H/WDh53y/ZoEa4XIEJh9SmbnflPRIsztpOuj959XbuQ8DDImwdXYwZ8J3UXvLeQsH+ToLiuS1omBvAiImNvlbQK+if8IXtsIXMh3IgRYDJqQFFcS0Y4TEvXAA/bB7h6CNLHdCcWVavmJ38uIuXdP0B+5ShNLA85wUbLnE+NyvXDYhhPkCq8Rc1v6hroVu1LdhNLwLI=
  provider: heroku
  app: rhantak-be4-final
