before_script:
- psql -c 'create database travis_ci_test;' -U postgres
language: ruby
rvm:
- 2.4.1
script:
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
services: postgresql
deploy:
  api_key:
    secure: IsSsnsgKFFPEp8PgiFVA5CZKqzVXKbtl6aEqguM3K3wx7zX/iJJ0dY81G0PQ0sgC3vNHWRk8e6O+iygBF+RJd3vwVqtEtommGdq+OdJRmf7irl7xV5WfnjYixnjDAp/qC5K3oMuAHURXRIRMXDGl0OZKJ71UlZcj7kCrP3haS3IE+ZCAf/mBqNCwjkn8wFxYsuvgIUT9Dmyu67nGMeV71g+1of+Q3mE/Q42DhpoIyYnAAAHbgvcCGpi1GPllDLpHdYEfElqtL08+L7Rq9uvFtalGCRtONgiqttvlMtjBepJjUkb7aa/h3LaPwoeF5sLRezKIz8D8gL+vQVqxnarF9x+uMl3BzWgEoCaKWvoZQX5J6Iww0H3U+xX01QLIVVbdHjHG5Ka3SsGiVYp6+CWXTFTwmtwYvEUXhpTcSmNyslwaPYKVQNCv+jFA76O8MNkUKXvQ+zkEmhSzTmWgiWbKixecn5RILSoNn2KE/AWTfYve6oSuhwq9Bd5GtT4XJuDBPtB+lNW7gV5ooIvfkpWioGlaasosR+s0/fD7dkpZkH2sIbqF3v0uEWwznyGYeCl8lIaxhzj6jK02kiD6UX/7UckB2XCFilddZF1EIMFqPmsXSyojM3537xaWNFe8XG/q4aBbbO1CG445vhNfXp8RWvNwVz1UmYpjRsG91qI+PuY=
  provider: heroku
  app: rhantak-be4-final
  on:
    repo: rhantak/be4_final
